### ISSUE TITLE
Add option to turn off vibration.

### ISSUE THREAD

**Issue by ryanpcmcquen** [burn123/PebbleMetronome#1]
Hello! I have tried several Pebble Metronomes, this is the best by far! But it would be nice if I could only use the visual arm sometimes. Any chance you would release an update that allowed that?

**Comment by cguldner** [comment]
Thanks for the feedback! I have now added this functionality in commit aa35576d0e33f5aeae653e6ce105fc7a28a993d2 and will be in the next release!

**Comment by ryanpcmcquen** [comment]
You rock!
