### ISSUE TITLE
Add option to show clock on top bar.

### ISSUE THREAD

**Issue by ryanpcmcquen** [burn123/PebbleMetronome#2]
The way some other apps do. This would allow me to stay in the app longer without switching out to check the time.

**Comment by cguldner** [comment]
Will be in the next release! Thank you for your feedback, I really appreciate it!

**Comment by ryanpcmcquen** [comment]
You're awesome, this app has been so helpful, do you have anywhere set up for donations?

**Comment by cguldner** [comment]
Thank you for your support! You don't need to give me anything, but if you really want to, I added a link to the github!
